version: '3'
services:
    redis:
        image: redis
        ports:
            - "6379:6379"

    app:
        build: ./
        ports:
            - "3000:3000"
        environment: 
            - PORT=3000
            - USE_CACHE=true
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        depends_on: 
            - redis